// AUTH-01 — POST /api/auth/signup
//
// Enumeration-resistant: returns identical 201 { ok: true } whether the email
// is new or already exists (D-22). Genuinely new users get a User row, an
// EMAIL_VERIFY VerificationCode, and an outbox email event — all in one tx.
// Existing-email branch runs `dummyBcryptCompare` so the request takes
// ~the same time as the new-user branch (timing parity).
//
// CSRF carve-out: signup is a pre-session route — no CSRF cookie exists yet,
// so calling verifyCsrf would 403 every legitimate request. The CSRF cookie is
// set on session establishment (verify-email / login / refresh).
export const runtime = 'nodejs';

import { NextResponse, type NextRequest } from 'next/server';
import { z } from 'zod';
import { zEmail } from '@/lib/server/zod-helpers';
import { prisma } from '@/lib/server/prisma';
import { redis } from '@/lib/server/redis';
import { createEmailLimiter } from '@/lib/server/middleware/rate-limit-by-email';
import { makeRequestContext, withRequestContext } from '@/lib/server/observability/request-context';
import { log } from '@/lib/server/observability/log';
import { hashPassword, generateVerificationCode } from '@/lib/server/auth';
import { isBanned } from '@/lib/server/auth/banned-passwords';
import { isPwned } from '@/lib/server/auth/hibp';
import { dummyBcryptCompare } from '@/lib/server/auth/dummy-bcrypt';
import { enqueueOutbox } from '@/lib/server/outbox';
import { slugify, ensureUniqueSlug } from '@/lib/server/slug';
import { getDefaultPlan } from '@/lib/server/subscriptions/default-plan';

const PASSWORD_MIN = Number(process.env.AUTH_PASSWORD_MIN_LENGTH ?? 10);
const VERIFICATION_TTL_MS = Number(process.env.AUTH_VERIFICATION_TTL_MIN ?? 15) * 60 * 1000;
// New clinics get a free trial before their first invoice is generated by
// the subscription-billing cron.
const TRIAL_DAYS = 30;

const Body = z.object({
  email: zEmail,
  password: z.string().min(1),
  // MediAfrica is multi-tenant: signup always creates a brand-new health
  // center (the signer becomes its OWNER). Joining an EXISTING clinic is a
  // separate flow — an OWNER/ADMIN invites staff from /personnel, which
  // reuses the password-reset UX instead of public self-signup.
  clinicName: z.string().trim().min(1).max(200),
});

const limiter = createEmailLimiter(redis ? { redis } : {}, {
  bucket: 'auth:signup',
  windowMs: 60 * 60 * 1000, // 1 hour (D-08)
  max: Number(process.env.AUTH_SIGNUP_RATE_LIMIT_MAX ?? 5),
  code: 'TOO_MANY_SIGNUP_ATTEMPTS',
  message: 'Too many signup attempts. Try again later.',
});

function formatIssues(err: z.ZodError) {
  return err.issues.map((e) => ({ path: e.path.join('.'), message: e.message }));
}

export async function POST(req: NextRequest): Promise<Response> {
  const ctx = makeRequestContext(req.headers);
  return withRequestContext(ctx, async () => {
    // 1. Body parse + Zod validation.
    const json = await req.json().catch(() => null);
    const parsed = Body.safeParse(json);
    if (!parsed.success) {
      const res = NextResponse.json(
        { error: 'VALIDATION_FAILED', issues: formatIssues(parsed.error) },
        { status: 400 },
      );
      res.headers.set('x-request-id', ctx.requestId);
      return res;
    }
    const { email, password, clinicName } = parsed.data;

    // 2. Password policy gates BEFORE looking up user (D-22 — keep the no-user
    //    and existing-user branches symmetric below).
    //    Banned check runs before length so a common short password ("password")
    //    surfaces the more specific PASSWORD_BANNED code rather than TOO_SHORT.
    if (isBanned(password)) {
      const res = NextResponse.json(
        { error: 'PASSWORD_BANNED', message: 'This password is too common.' },
        { status: 400 },
      );
      res.headers.set('x-request-id', ctx.requestId);
      return res;
    }
    if (password.length < PASSWORD_MIN) {
      const res = NextResponse.json(
        {
          error: 'PASSWORD_TOO_SHORT',
          message: `Password must be at least ${PASSWORD_MIN} characters`,
        },
        { status: 400 },
      );
      res.headers.set('x-request-id', ctx.requestId);
      return res;
    }
    if (process.env.PASSWORD_HIBP_CHECK === '1' && (await isPwned(password))) {
      const res = NextResponse.json(
        {
          error: 'PASSWORD_PWNED',
          message: 'This password appeared in a known data breach.',
        },
        { status: 400 },
      );
      res.headers.set('x-request-id', ctx.requestId);
      return res;
    }

    // 3. Per-email rate limit.
    const rateFail = await limiter.check(req, email);
    if (rateFail) return rateFail;

    // 3.5. A brand-new clinic needs a plan to subscribe to. Checked before
    // touching the existing-email branch so a misconfigured platform (no
    // active Plan) fails the same way regardless of whether the email is
    // new or not — no enumeration signal either way.
    const defaultPlan = await getDefaultPlan(prisma);
    if (!defaultPlan) {
      const res = NextResponse.json(
        { error: 'SIGNUP_UNAVAILABLE', message: 'Signup is temporarily unavailable.' },
        { status: 503 },
      );
      res.headers.set('x-request-id', ctx.requestId);
      return res;
    }

    // 4. Existing-email branch — return identical 201 with timing parity (D-22).
    const existing = await prisma.user.findUnique({
      where: { email },
      select: { id: true },
    });
    if (existing) {
      await dummyBcryptCompare(password);
      log.info('signup duplicate (enumeration-resist)');
      const res = NextResponse.json({ ok: true }, { status: 201 });
      res.headers.set('x-request-id', ctx.requestId);
      return res;
    }

    // 5. New-user branch — hash + create User + Organization (the new
    // clinic) + OWNER membership + TRIALING Subscription + ClinicSettings +
    // VerificationCode + outbox, all in one tx.
    const passwordHash = await hashPassword(password);
    const code = generateVerificationCode();
    const expiresAt = new Date(Date.now() + VERIFICATION_TTL_MS);

    // Resolve the slug via plain (non-transactional) existence checks before
    // opening the transaction below. Retrying `tx.organization.create` inside
    // an interactive transaction is unsafe: Postgres aborts the whole
    // transaction on the first error, so every retry after a genuine
    // collision fails too — even against slugs that are actually free —
    // until ensureUniqueSlug exhausts its attempts and throws.
    const orgSlug = await ensureUniqueSlug(slugify(clinicName), async (candidate) => {
      const existing = await prisma.organization.findUnique({
        where: { slug: candidate },
        select: { id: true },
      });
      if (existing) {
        throw Object.assign(new Error('slug taken'), { code: 'P2002' });
      }
      return candidate;
    });

    await prisma.$transaction(async (tx) => {
      const user = await tx.user.create({
        data: { email, passwordHash },
        select: { id: true },
      });

      const org = await tx.organization.create({
        data: { slug: orgSlug, name: clinicName, ownerId: user.id },
        select: { id: true },
      });
      const organizationId = org.id;

      await tx.organizationMember.create({
        data: { organizationId, userId: user.id, role: 'OWNER' },
      });

      const trialEndsAt = new Date(Date.now() + TRIAL_DAYS * 24 * 60 * 60 * 1000);
      await tx.subscription.create({
        data: {
          organizationId,
          planId: defaultPlan.id,
          status: 'TRIALING',
          trialEndsAt,
          currentPeriodEnd: trialEndsAt,
        },
      });

      await tx.clinicSettings.create({
        data: { organizationId, name: clinicName },
      });

      await tx.verificationCode.create({
        data: {
          userId: user.id,
          code,
          type: 'EMAIL_VERIFY',
          expiresAt,
        },
      });
      await enqueueOutbox(tx, {
        kind: 'email.verification_code',
        payload: {
          to: email,
          code,
          expiresAt: expiresAt.toISOString(),
        },
      });
    });

    log.info('signup new user');
    const res = NextResponse.json({ ok: true }, { status: 201 });
    res.headers.set('x-request-id', ctx.requestId);
    return res;
  });
}
